--
-- PostgreSQL database dump
--

-- Dumped from database version 16.3
-- Dumped by pg_dump version 16.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: product; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.product (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    price double precision NOT NULL,
    quantity integer NOT NULL,
    supplier_id integer NOT NULL
);


ALTER TABLE public.product OWNER TO postgres;

--
-- Name: product_batch; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.product_batch (
    id bigint NOT NULL,
    expiration timestamp(6) without time zone NOT NULL,
    quantity integer NOT NULL,
    product_id integer NOT NULL
);


ALTER TABLE public.product_batch OWNER TO postgres;

--
-- Name: product_batch_id_seq1; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.product_batch ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_batch_id_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: product_id_seq1; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.product ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_id_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: purchase_order; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.purchase_order (
    id bigint NOT NULL,
    comment character varying(255),
    date timestamp(6) without time zone NOT NULL,
    quantity integer NOT NULL,
    status smallint NOT NULL,
    total_value double precision NOT NULL,
    customer_id integer NOT NULL,
    manager_id integer NOT NULL,
    product_id integer NOT NULL
);


ALTER TABLE public.purchase_order OWNER TO postgres;

--
-- Name: purchase_order_id_seq1; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.purchase_order ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.purchase_order_id_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sales_order; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sales_order (
    id bigint NOT NULL,
    comment character varying(255),
    date timestamp(6) without time zone NOT NULL,
    quantity integer NOT NULL,
    status smallint NOT NULL,
    total_value double precision NOT NULL,
    customer_id integer NOT NULL,
    manager_id integer NOT NULL,
    product_id bigint NOT NULL,
    batch_id bigint NOT NULL,
    product_batch integer NOT NULL,
    productid integer NOT NULL
);


ALTER TABLE public.sales_order OWNER TO postgres;

--
-- Name: sales_order_id_seq1; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.sales_order ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sales_order_id_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    role smallint NOT NULL
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: product_batch product_batch_pkey1; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product_batch
    ADD CONSTRAINT product_batch_pkey1 PRIMARY KEY (id);


--
-- Name: product product_pkey1; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product
    ADD CONSTRAINT product_pkey1 PRIMARY KEY (id);


--
-- Name: purchase_order purchase_order_pkey1; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.purchase_order
    ADD CONSTRAINT purchase_order_pkey1 PRIMARY KEY (id);


--
-- Name: sales_order sales_order_pkey1; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sales_order
    ADD CONSTRAINT sales_order_pkey1 PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: product_batch fk4o8xo3bdl8yv75cf9glafk6tv; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product_batch
    ADD CONSTRAINT fk4o8xo3bdl8yv75cf9glafk6tv FOREIGN KEY (product_id) REFERENCES public.product(id);


--
-- Name: sales_order fkgxxf80tmatpyxox6bn6r49q5k; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sales_order
    ADD CONSTRAINT fkgxxf80tmatpyxox6bn6r49q5k FOREIGN KEY (batch_id) REFERENCES public.product_batch(id);


--
-- Name: sales_order fknpltmxlfnhsjtmvh6hcjjtoyy; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sales_order
    ADD CONSTRAINT fknpltmxlfnhsjtmvh6hcjjtoyy FOREIGN KEY (product_id) REFERENCES public.product(id);


--
-- Name: purchase_order fkorudvkngcr1iy3dkrnfqxgy6n; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.purchase_order
    ADD CONSTRAINT fkorudvkngcr1iy3dkrnfqxgy6n FOREIGN KEY (product_id) REFERENCES public.product(id);


--
-- PostgreSQL database dump complete
--

